### ISSUE TITLE
.stl files for the cheesebox missing?

### ISSUE THREAD

**Issue by viragored** [CrazyRobMiles/PICO-MIDI-Cheesebox#1]
Am I missing something? The Hackspace #48 article says we can download and 3D-print a custom case. I was expecting a case for the controller, and not just a case for the Pico. The 'case' folder has two files in it, the top and bottom for a Pico case.
Are the files to print the "cheesebox" available somewhere?
Edit:
I decided to see if I could learn enough OpenSCAD to design a printable cheese box - the result is now in Thingiverse
https://www.thingiverse.com/thing:5147866

**Comment by CrazyRobMiles** [comment]
Sorry about that. I completely forgot. The files are there now. Your build looks awesome. I hope it works well for you.
